name: Close old issues that need reply

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'pybamm-team'
    steps:
      - name: Close old issues that need reply
        uses: dwieeb/needs-reply@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-label: needs-reply
