name: Create a release reminder

on:
  schedule:
     # Run at 10 am UTC on days-of-month 1 and 28 in January, May, and September.
     - cron: "0 10 1,28 1,5,9 *"

permissions:
  contents: read
  issues: write

jobs:
  remind:
    if: github.repository_owner == 'pybamm-team'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/release_reminder.md
