name: PyBaMM

on:
  workflow_dispatch:
  pull_request:

jobs:
  pre_job:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: "never"
          cancel_others: "true"
          paths_ignore: '["**/README.md"]'

  style:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Check style
        run: |
          python -m pip install pre-commit
          pre-commit run ruff

  build:
    needs: style
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Check out PyBaMM repository
        uses: actions/checkout@v3

      # Install and cache apt packages
      - name: Install Linux system dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1.3.0
        if: matrix.os == 'ubuntu-latest'
        with:
          packages: gfortran gcc graphviz pandoc
          execute_install_scripts: true

      # dot -c is for registering graphviz fonts and plugins
      - name: Install OpenBLAS and TeXLive for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo dot -c
          sudo apt-get install libopenblas-dev texlive-latex-extra dvipng

      - name: Install macOS system dependencies
        if: matrix.os == 'macos-latest'
        env:
          # Homebrew environment variables
          HOMEBREW_NO_INSTALL_CLEANUP: 1
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_COLOR: 1
          # Speed up CI
          NONINTERACTIVE: 1
        run: |
          brew analytics off
          brew update
          brew install graphviz openblas

      - name: Install Windows system dependencies
        if: matrix.os == 'windows-latest'
        run: choco install graphviz --version=8.0.5

      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install PyBaMM dependencies
        run: |
          pip install --upgrade pip wheel setuptools nox
          pip install -e .[all,docs]

      - name: Cache pybamm-requires nox environment for GNU/Linux
        uses: actions/cache@v3
        if: matrix.os == 'ubuntu-latest'
        with:
          path: |
            # Repository files
            ${{ github.workspace }}/pybind11/
            ${{ github.workspace }}/install_KLU_Sundials/
            # Headers and dynamic library files for SuiteSparse and SUNDIALS
            ${{ env.HOME }}/.local/lib/
            ${{ env.HOME }}/.local/include/
            ${{ env.HOME }}/.local/examples/
          key: nox-pybamm-requires-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/install_KLU_Sundials.py') }}

      - name: Install SuiteSparse and SUNDIALS on GNU/Linux
        if: matrix.os == 'ubuntu-latest'
        run: nox -s pybamm-requires

      - name: Run unit tests for GNU/Linux with Python 3.8, 3.9, and 3.10 and for macOS and Windows with all Python versions
        if: (matrix.os == 'ubuntu-latest' && matrix.python-version != 3.11) || (matrix.os != 'ubuntu-latest')
        run: nox -s unit

      - name: Run unit tests for GNU/Linux with Python 3.11 and generate coverage report
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == 3.11
        run: nox -s coverage

      - name: Upload coverage report
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == 3.11
        uses: codecov/codecov-action@v3.1.4

      - name: Run integration tests for GNU/Linux with Python 3.11
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == 3.11
        run: nox -s integration

      - name: Install docs dependencies and run doctests for GNU/Linux with Python 3.11
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == 3.11
        run: nox -s doctests

      - name: Install dev dependencies and run example tests for GNU/Linux with Python 3.11
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == 3.11
        run: nox -s examples
